Repository Bamdoliro/Bamdoliro, pull requests merged in 2023-01, with the labels that each got.

#2 Chore
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  public/favicon.png
  public/index.html
  src/Assets/.gitkeep
  src/Components/.gitkeep
  src/Pages/.gitkeep
  src/assets/arrow.svg
  src/assets/background01.svg
  src/assets/logo.svg
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/Main/index.tsx
  src/components/Main/style.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/style.ts
  src/components/index.tsx
  src/fonts/Pretendard-Bold.woff
  src/fonts/Pretendard-Medium.woff
  src/fonts/Pretendard-SemiBold.woff
  src/pages/Main.tsx
  src/pages/index.tsx
  src/shared/styles/global.style.ts
  src/shared/styles/text.ts
  src/shared/styles/theme.ts
Labels: ⚙️ Setting, 🔨 Refactor

#3 FIX :: Delete 에러 고침
  .eslintrc.js
Labels: 🐞 Bug

#4 FEAT :: Teammate 페이지 개발 및 App.tsx에 추가
  package-lock.json
  package.json
  src/App.tsx
  src/assets/dummyData/generation.json
  src/assets/dummyData/index.ts
  src/assets/dummyData/profiles.json
  src/assets/gitHubURLArrow.svg
  src/assets/profiles/IronPermMan.png
  src/assets/profiles/index.ts
  src/components/Teammate/index.tsx
  src/components/Teammate/style.ts
  src/components/atoms/index.ts
  src/components/common/GenerationRadio/index.tsx
  src/components/common/Profile/index.tsx
  src/components/common/Profile/style.ts
  src/components/common/ProfileGroup/index.tsx
  src/components/common/ProfileGroup/style.ts
  src/components/common/RadioGroup/index.tsx
  src/components/common/RadioGroup/style.ts
  src/components/context/index.ts
  src/pages/Teammate.tsx
  src/pages/index.tsx
Labels: ✨ Feature

#6 Feat/bamdoliro teammate
  src/App.tsx
  src/assets/dummyData/index.ts
  src/atoms/index.ts
  src/components/GenerationRadio/index.tsx
  src/components/ProfileGroup/index.tsx
  src/components/ProfileGroup/style.ts
  src/components/RadioGroup/index.tsx
  src/components/RadioGroup/style.ts
  src/components/Teammate/index.tsx
  src/components/Teammate/style.ts
  src/components/common/Button/index.tsx
  src/components/common/Profile/style.ts
  src/components/context/index.ts
  src/data/generation.json
  src/data/profiles.json
Labels: ✨ Feature, 🔨 Refactor
